# Exercise 4.10 Coding Etiquette & Excel Reporting 1

# Table of contents:

# Part 1

Questions#1: Import the data set you exported in Exercise 4.9 into a new Jupyter notebook. This should be the merged version of your data that contains the new customers column.

Questions#2: Consider any security implications that might exist for this new data. You’ll need to address any PII data in the data before continuing your analysis.

Questions#3: The Instacart officers are interested in comparing customer behavior in different geographic areas. Create a regional segmentation of the data. You’ll need to create a “Region” column based on the “State” column from your customers data set.

   - Use the region information in this Wikipedia article to create your column (you only need to create regions, not divisions). 

   - Determine whether there’s a difference in spending habits between the different U.S. regions. (Hint: You can do this by crossing the variable you just created with the spending flag.)

Question#4: The Instacart CFO isn’t interested in customers who don’t generate much revenue for the app. Create an exclusion flag for low-activity customers (customers with less than 5 orders) and exclude them from the data. Make sure you export this sample.

Question#5: The marketing and business strategy units at Instacart want to create more-relevant marketing strategies for different products and are, thus, curious about customer profiling in their database. Create a profiling variable based on age, income, certain goods in the “department_id” column, and number of dependents. You might also use the “orders_day_of_the_week” and “order_hour_of_day” columns if you can think of a way they would impact customer profiles. (Hint: As an example, try thinking of what characteristics would lead you to the profile “Single adult” or “Young parent.”)

Question#6: Create an appropriate visualization to show the distribution of profiles.

In [2]:
# Import libraries
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
import scipy

In [3]:
# Assign path
path = r'C:\Users\djval\Google Drive\Career\Career Foundry\Data Immerson\Achievement 4\10-2021 Instacart Basket Analysis'

In [4]:
path

'C:\\Users\\djval\\Google Drive\\Career\\Career Foundry\\Data Immerson\\Achievement 4\\10-2021 Instacart Basket Analysis'

# Import the data set you exported in Exercise 4.9 into a new Jupyter notebook. This should be the merged version of your data that contains the new customers column.

In [5]:
# Import exported data set from Exercise 4.9
df_ords_prods_cust_merged = pd.read_pickle(os.path.join(path,'02 Data','Prepared Data','orders_products_customer_merged.pkl'))

In [5]:
# Check shape
df_ords_prods_cust_merged.shape

(32434212, 32)

In [6]:
# Check headers
df_ords_prods_cust_merged.head(1)

,order_id,product_id,add_to_cart_order,reordered,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_name,...,frequency_flag,first_name,sur_name,gender,state,age,date_joined,number_of_dependants,fam_status,income
0,2,33120,1,1,202279,3,5,9,8.0,Organic Egg Whites,...,Non-frequent customer,Paul,Coleman,Male,Idaho,57,2/6/2020,3,married,98119

# Consider any security implications that might exist for this new data. You’ll need to address any PII data in the data before continuing your analysis.

Consider any security implications that might exist for this new data. Address any PII data in the data.

There is PII data in this data set. Below is a list of data that can be used to traced back to a particular person.

- first_name
- Sur_name

These names cannot be used in this analysis. The names will not be deleted permanently. Instead, a copy of the data set will be made without these two columns.

In [7]:
# Create a new version of df_ords_prods_cust_merged without the "first_name" & "sur_name" columns called df_ords_prods_cust_merged_2
df_ords_prods_cust_merged_2 = df_ords_prods_cust_merged.drop(columns = ['first_name','sur_name'])

In [8]:
# Check headers without PII data
df_ords_prods_cust_merged_2.head(1)

,order_id,product_id,add_to_cart_order,reordered,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_name,...,spending_flag,median_days_since_prior_order,frequency_flag,gender,state,age,date_joined,number_of_dependants,fam_status,income
0,2,33120,1,1,202279,3,5,9,8.0,Organic Egg Whites,...,Low spender,24.0,Non-frequent customer,Male,Idaho,57,2/6/2020,3,married,98119

# The Instacart officers are interested in comparing customer behavior in different geographic areas. Create a regional segmentation of the data. You’ll need to create a “Region” column based on the “State” column from your customers data set.

In [9]:
# Check state names and value counts
df_ords_prods_cust_merged_2['state'].value_counts(dropna = False)

Pennsylvania            667710
California              660447
Rhode Island            657655
Georgia                 657072
New Mexico              655143
Arizona                 654545
North Carolina          652338
Oklahoma                652263
Alaska                  649020
Minnesota               648408
Massachusetts           647000
Wyoming                 644929
Virginia                642075
Missouri                641313
Texas                   641058
Colorado                639752
Maine                   639149
North Dakota            638999
Alabama                 638617
Louisiana               638174
Kansas                  637991
Delaware                637447
South Carolina          637348
Oregon                  636949
Arkansas                636706
New York                636697
Nevada                  636697
Montana                 635835
South Dakota            634340
Illinois                633490
Hawaii                  633445
Washington              633421
Mississippi             633103
Kentucky                632905
Michigan                631622
Florida                 629582
Ohio                    629001
Wisconsin               628552
New Jersey              628292
Indiana                 627768
Maryland                627278
Nebraska                626297
Iowa                    626029
Connecticut             623582
Tennessee               618396
New Hampshire           616006
District of Columbia    614293
West Virginia           612955
Utah                    612451
Vermont                 612256
Idaho                   607811
Name: state, dtype: int64

# Use the region information in this Wikipedia article to create your column (you only need to create regions, not divisions).

In [10]:
# Create regions
result = []

for value in df_ords_prods_cust_merged_2['state']:
    if (value == 'Maine') or (value == 'New Hampshire') or (value == 'Vermont') or (value == 'Massachusetts') or (value == 'Rhode Island') or (value == 'Connecticut') or (value == 'New York') or (value == 'Pennsylvania') or (value =='New Jersey'):
        result.append('Northeast')
    elif (value == 'Wisconsin') or (value == 'Michigan') or (value == 'Illinois') or (value == 'Indiana') or (value == 'Ohio') or (value == 'North Dakota') or (value == 'South Dakota') or (value == 'Nebraska') or (value == 'Kansas') or (value == 'Minnesota') or (value == 'Iowa') or (value == 'Missouri'):
        result.append('Midwest')
    elif (value == 'Deleware') or (value == 'Maryland') or (value == 'District of Columbia') or (value == 'Virginia') or (value == 'West Virginia') or (value == 'North Carolina') or (value == 'South Carolina') or (value == 'Georgia') or (value == 'Florida') or (value == 'Kentucky') or (value == 'Tennessee') or (value == 'Mississippi') or (value == 'Alabama') or (value == 'Oklahoma') or (value == 'Texas') or (value == 'Arkansas') or (value == 'Louisiana'):
        result.append('South')
    else:
        result.append('West')

In [11]:
# Print the result
result

['West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 ...]

In [12]:
# Create new column within dataframe and set it equal to result
df_ords_prods_cust_merged_2['region'] = result

In [13]:
# Check the count for each region
df_ords_prods_cust_merged_2['region'].value_counts(dropna = False)

South        10164163
West          8937892
Midwest       7603810
Northeast     5728347
Name: region, dtype: int64

Confirm if region totals match index total
10164163 + 8937892 + 7603810 + 5728347 = 32434212

In [14]:
df_ords_prods_cust_merged_2.shape

(32434212, 31)

Number of rows match.

# Determine whether there’s a difference in spending habits between the different U.S. regions.

In [15]:
# Create crosstab
crosstab = pd.crosstab(df_ords_prods_cust_merged_2['region'],df_ords_prods_cust_merged_2['spending_flag'],dropna = False)

In [16]:
# Check results of crosstab
crosstab

spending_flag  High spender  Low spender
region
Midwest              156115      7447695
Northeast            108336      5620011
South                193575      9970588
West                 177376      8760516

In [17]:
# Get percent of high spenders for Midwest vs their total population (156,115+7,447,695=7,603,810)
Midwest = (156115/7603810)*100

In [18]:
Midwest

2.053115477635554

In [19]:
# Get percent of high spenders for Northeast ovs their total population (108,336+5,620,011=5,728,347)
Northeast = (108336/5728347)*100

In [20]:
Northeast

1.891226212378545

In [21]:
# Get percent of high spenders for South vs their total population (193,575+9,970,588=10,164,163)
South = (193575/10164163)*100

In [22]:
South

1.9044853963872874

In [23]:
# Get percent of high spenders for West vs their total population (177,376+8,760,516=8,937,892)
West = (177376/8760516)*100

In [24]:
West

2.0247209182655452

The  difference in spedning habits between the regions is not significant. The largest difference is between the Midwest and Northest with a 0.16% (47,779 high spenders). The South has the most number of High Spenders but the Midwest has the highest percentage of high spender vs their total population.

# The Instacart CFO isn’t interested in customers who don’t generate much revenue for the app. Create an exclusion flag for low-activity customers (customers with less than 5 orders) and exclude them from the data. Make sure you export this sample.

In [25]:
# Create low-activity flag for customers with less than 5 orders (exercise 4.8)
df_ords_prods_cust_merged_2.loc[df_ords_prods_cust_merged_2['max_order'] < 5, 'exclusion_flag'] = 'low activity customer'

In [26]:
# Create non-low-activity flag for customers with more than 5 orders (exercise 4.8)
df_ords_prods_cust_merged_2.loc[df_ords_prods_cust_merged_2['max_order'] >= 5, 'exclusion_flag'] = 'non low activity customer'

In [27]:
# Check exclusion flag
df_ords_prods_cust_merged_2['exclusion_flag'].value_counts(dropna = False)

non low activity customer    30992664
low activity customer         1441548
Name: exclusion_flag, dtype: int64

In [28]:
# Create a subset data set with only low-activity customers (exercise 4.4)
df_ords_prods_low_activity_cust = df_ords_prods_cust_merged_2[df_ords_prods_cust_merged_2['exclusion_flag']=='low activity customer']

In [29]:
# Check the value for max orders to confim no orders are above 5
df_ords_prods_low_activity_cust['max_order'].value_counts()

4    754260
3    687288
Name: max_order, dtype: int64

In [30]:
# Create a subset data set with only non low-activity customers (exercise 4.4)
df_ords_prods_non_low_activity_cust = df_ords_prods_cust_merged_2[df_ords_prods_cust_merged_2['exclusion_flag']=='non low activity customer']

In [31]:
# Check the value for max orders to confim no orders are below 5
df_ords_prods_non_low_activity_cust['max_order'].value_counts().sort_index()

5      793833
6      812032
7      804712
8      812641
9      810819
       ...
95      59894
96      40469
97      44969
98      44604
99    1172222
Name: max_order, Length: 95, dtype: int64

In [32]:
# Export subset for low-activity customers
df_ords_prods_low_activity_cust.to_pickle(os.path.join(path,'02 Data','Prepared Data','orders_producsts_low_activity_cust.pkl'))

In [33]:
# Export subset for non-low-activity customers
df_ords_prods_non_low_activity_cust.to_pickle(os.path.join(path,'02 Data','Prepared Data','orders_producsts_non_low_activity_cust.pkl'))

# The marketing and business strategy units at Instacart want to create more-relevant marketing strategies for different products and are, thus, curious about customer profiling in their database. Create a profiling variable based on age, income, certain goods in the “department_id” column, and number of dependents. You might also use the “orders_day_of_the_week” and “order_hour_of_day” columns if you can think of a way they would impact customer profiles. (Hint: As an example, try thinking of what characteristics would lead you to the profile “Single adult” or “Young parent.”)

The marketing and business strategy units at Instacart want to create more-relevant marketing strategies for DIFFERENT PRODUCTS. Therefore, I will look at the relationship between certain products and certain customers to define these marketing strategies to make the more relevant and successful. 

I will start by creating customer profile variables based on age, income, and number of dependents. I will also create variables based on orders_day_of_the_week, order_hour_of_day.

In [32]:
# Check the age range of customers 
df_ords_prods_cust_merged_2['age'].value_counts().sort_index()

18    500872
19    520183
20    503309
21    512977
22    514409
       ...
77    502641
78    495703
79    530298
80    515657
81    509727
Name: age, Length: 64, dtype: int64

In [33]:
# Create age group and if-statement with For-loops for these age groups. 

age_group = []

for value in df_ords_prods_cust_merged_2['age']:
    if value <= 20:
        age_group.append('18-20')
    elif (value > 20) and (value <= 30):
        age_group.append('21-30')
    elif (value > 30) and (value <= 40):
        age_group.append('31-40')
    elif (value > 40) and (value <= 50):
        age_group.append('41-50')
    elif (value > 50) and (value <= 60):
        age_group.append('51-60')
    elif (value > 60) and (value <= 70):
        age_group.append('61-70')
    elif (value > 70) and (value <= 80):
        age_group.append('71-80')
    elif (value > 80) and (value <= 82):
        age_group.append('80+')    
    else:
        result.append('Not in age category')

In [34]:
# Create new age_group column set it equal to age_group
df_ords_prods_cust_merged_2['age_group'] = age_group

In [35]:
# Confirm resutls from new age group column
df_ords_prods_cust_merged_2['age_group'].value_counts().sort_index()

18-20    1524364
21-30    5081136
31-40    5075016
41-50    5096563
51-60    5064860
61-70    5009316
71-80    5073230
80+       509727
Name: age_group, dtype: int64

In [36]:
# Check the income ranges for customers
df_ords_prods_cust_merged_2['income'].value_counts().sort_index()

25903      20
25911      28
25937      39
25941      31
25955     392
         ...
584097    826
590790     54
591089    176
592409    318
593901    640
Name: income, Length: 108012, dtype: int64

In [37]:
customer_income = df_ords_prods_cust_merged_2['income'].value_counts().sort_index()

In [38]:
customer_income.to_clipboard()

In [39]:
# Create income brackets mainly based on current income tax brackets and if-statement with For-loops for income

income = []

for value in df_ords_prods_cust_merged_2['income']:
    if value <= 25000: 
        income.append('0-025000')
    elif (value > 25000) and (value <= 40000):
        income.append('025000-040000')
    elif (value > 40000) and (value <= 80000):
        income.append('040000-080000')
    elif (value > 80000) and (value <= 120000):
        income.append('080000-120000')
    elif (value > 120000) and (value <= 160000):
        income.append('120000-160000')
    elif (value > 160000) and (value <= 210000):
        income.append('160000-210000')
    elif (value > 210000) and (value <= 523000):
        income.append('210000-523000')
    elif (value > 523000):
        income.append('523000+')
    else: 
        income.append('other')

In [40]:
# Create new imcome_range column and set it equal to income
df_ords_prods_cust_merged_2['income_range'] = income

In [41]:
# Check results of income_range
df_ords_prods_cust_merged_2['income_range'].value_counts().sort_index()

025000-040000     1728992
040000-080000     9856079
080000-120000    11269859
120000-160000     7368794
160000-210000     1967249
210000-523000      228628
523000+             14611
Name: income_range, dtype: int64

In [42]:
# Check the range of number of dependents
df_ords_prods_cust_merged_2['number_of_dependants'].value_counts().sort_index()

0    8105197
1    8088310
2    8098387
3    8142318
Name: number_of_dependants, dtype: int64

In [43]:
# Create parent/non parent with if-statement with the loc() Function
df_ords_prods_cust_merged_2.loc[df_ords_prods_cust_merged_2['number_of_dependants'] == 0, 'parental_status'] = 'non parent'
df_ords_prods_cust_merged_2.loc[df_ords_prods_cust_merged_2['number_of_dependants'] >= 1, 'parental_status'] = 'parent'

In [44]:
# Check results for parent status
df_ords_prods_cust_merged_2['parental_status'].value_counts(dropna = False)

parent        24329015
non parent     8105197
Name: parental_status, dtype: int64

In [45]:
# Create variable for day of week
df_ords_prods_cust_merged_2['orders_day_of_week'].value_counts().sort_index()

0    6209632
1    5665830
2    4217766
3    3844096
4    3787193
5    4209449
6    4500246
Name: orders_day_of_week, dtype: int64

In [46]:
# Create crosstab to confirm day 0 and 6 are weekend days
orders_per_day_of_week = pd.crosstab(df_ords_prods_cust_merged_2['orders_day_of_week'],df_ords_prods_cust_merged_2['order_number'],dropna = False)

In [47]:
orders_per_day_of_week

order_number,1,2,3,4,5,6,7,8,9,10,...,90,91,92,93,94,95,96,97,98,99
orders_day_of_week,,,,,,,,,,,,,,,,,,,,,
0,425492,405218,410553,362150,320225,291230,265958,241846,220158,200405,...,2368,2437,2300,2140,2063,1591,1802,1736,1545,1533
1,356860,358977,355526,316083,279922,252262,231091,209510,193341,180276,...,3004,2772,2987,2747,2831,2788,2371,2488,2010,2132
2,266523,266181,268233,239499,212398,194483,172856,160945,143619,133435,...,2332,2726,2432,2067,2334,1972,2022,1915,1835,1803
3,240204,239489,239288,215812,192414,174384,157876,142351,132079,119619,...,2746,2174,2276,2357,2187,1889,2093,1713,1919,1694
4,229484,228583,230897,205827,188705,166201,153604,139661,130274,118940,...,2408,2452,2276,2390,2335,2207,1919,2066,2063,1811
5,253702,254258,256230,225274,202777,184563,165207,152672,143494,131608,...,2441,2515,2228,2000,1787,2426,1928,1989,2088,1983
6,305819,295624,289982,255653,231944,209119,187253,172160,157504,144403,...,1910,1783,1730,1706,1674,1653,1611,1459,1397,1478

In [48]:
# Creating weekday column with loc function 

df_ords_prods_cust_merged_2.loc[df_ords_prods_cust_merged_2['orders_day_of_week'] == 0, 'weekday'] = 'Saturday'
df_ords_prods_cust_merged_2.loc[df_ords_prods_cust_merged_2['orders_day_of_week'] == 1, 'weekday'] = 'Sunday'
df_ords_prods_cust_merged_2.loc[df_ords_prods_cust_merged_2['orders_day_of_week'] == 2, 'weekday'] = 'Monday'
df_ords_prods_cust_merged_2.loc[df_ords_prods_cust_merged_2['orders_day_of_week'] == 3, 'weekday'] = 'Tuesday'
df_ords_prods_cust_merged_2.loc[df_ords_prods_cust_merged_2['orders_day_of_week'] == 4, 'weekday'] = 'Wednesday'
df_ords_prods_cust_merged_2.loc[df_ords_prods_cust_merged_2['orders_day_of_week'] == 5, 'weekday'] = 'Thursday'
df_ords_prods_cust_merged_2.loc[df_ords_prods_cust_merged_2['orders_day_of_week'] == 6, 'weekday'] = 'Friday'

In [49]:
# Check order totals for weekdays 
df_ords_prods_cust_merged_2['weekday'].value_counts().sort_index()

Friday       4500246
Monday       4217766
Saturday     6209632
Sunday       5665830
Thursday     4209449
Tuesday      3844096
Wednesday    3787193
Name: weekday, dtype: int64

In [50]:
# Create variable for part of the day
df_ords_prods_cust_merged_2['order_hour_of_day'].value_counts().sort_index()

0      218942
1      115786
2       69431
3       51317
4       53283
5       88057
6      290770
7      891928
8     1719952
9     2456661
10    2764390
11    2738585
12    2620800
13    2663272
14    2691563
15    2664522
16    2537469
17    2089452
18    1637922
19    1259382
20     977017
21     796362
22     634737
23     402612
Name: order_hour_of_day, dtype: int64

I will define the hours of the day as:
Midnight to Noon (0-11) as Morning
Noon to 5pm (12-5) as Afternoon
6pm to Midanight (6-23) as Evening

In [51]:
result = []

for value in df_ords_prods_cust_merged_2['order_hour_of_day']:
    if value <= 11: 
        result.append('Morning')
    elif (value > 11) and (value <= 17):
        result.append('Afternoon')
    elif (value > 17) and (value <= 24):
        result.append('Evening')
    else: 
        result.append('other')

In [52]:
result

['Morning',
 'Morning',
 'Morning',
 'Afternoon',
 'Morning',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Morning',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Morning',
 'Morning',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Morning',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Evening',
 'Evening',
 'Morning',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Morning',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Evening',
 'Afternoon',
 'Evening',
 'Evening',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Evening',
 'Afternoon',
 'Evening',
 'Evening',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Evening',
 'Afternoon',
 'Evening',
 'Evening',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Evening',
 'Evening',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Evening',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Evening',
 'Morning',
 'Evening',
 'Evening',
 'Evening',
 'Evening',
 'Evening',
 'Evening',
 'Morning',
 'Evening',
 'Evening',
 'Morning',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Evening',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Evening',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Evening',
 'Evening',
 'Evening',
 'Evening',
 'Evening',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Morning',
 'Evening',
 'Evening',
 'Evening',
 'Evening',
 'Evening',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Morning',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Evening',
 'Evening',
 'Afternoon',
 'Evening',
 'Evening',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Evening',
 'Morning',
 'Evening',
 'Evening',
 'Evening',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Evening',
 'Evening',
 'Evening',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Evening',
 'Evening',
 'Evening',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Evening',
 'Afternoon',
 'Evening',
 'Evening',
 'Evening',
 'Evening',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Evening',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Morning',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Evening',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Evening',
 'Morning',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Evening',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Morning',
 'Morning',
 'Afternoon',
 'Morning',
 'Morning',
 'Morning',
 'Evening',
 'Evening',
 'Evening',
 'Evening',
 'Afternoon',
 'Morning',
 'Evening',
 'Morning',
 'Morning',
 'Evening',
 'Afternoon',
 'Morning',
 'Morning',
 'Morning',
 'Morning',
 'Morning',
 'Morning',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Evening',
 'Morning',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Morning',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Evening',
 'Morning',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Morning',
 'Morning',
 'Morning',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Morning',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Morning',
 'Morning',
 'Morning',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Morning',
 'Morning',
 'Morning',
 'Morning',
 'Morning',
 'Morning',
 'Afternoon',
 'Morning',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Morning',
 'Morning',
 'Morning',
 'Morning',
 'Afternoon',
 'Morning',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Morning',
 'Morning',
 'Morning',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Evening',
 'Morning',
 'Morning',
 'Morning',
 'Morning',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Evening',
 'Morning',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Morning',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Morning',
 'Morning',
 'Morning',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Morning',
 'Morning',
 'Evening',
 'Afternoon',
 'Evening',
 'Evening',
 'Morning',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Evening',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Morning',
 'Evening',
 'Evening',
 'Evening',
 'Evening',
 'Afternoon',
 'Evening',
 'Morning',
 'Afternoon',
 'Morning',
 'Evening',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Evening',
 'Morning',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Morning',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Morning',
 'Morning',
 'Evening',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Morning',
 'Evening',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Evening',
 'Morning',
 'Afternoon',
 'Morning',
 'Evening',
 'Afternoon',
 'Morning',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Evening',
 'Morning',
 'Morning',
 'Morning',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Evening',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Evening',
 'Morning',
 'Morning',
 'Afternoon',
 'Morning',
 'Evening',
 'Afternoon',
 'Evening',
 'Morning',
 'Morning',
 'Evening',
 'Evening',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Evening',
 'Morning',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Evening',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Evening',
 'Morning',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Morning',
 'Morning',
 'Afternoon',
 'Evening',
 'Morning',
 'Morning',
 'Morning',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Morning',
 'Morning',
 'Afternoon',
 'Morning',
 'Evening',
 'Morning',
 'Afternoon',
 'Evening',
 'Afternoon',
 'Evening',
 ...]

In [53]:
# Create new part of the day column and set it equal to result
df_ords_prods_cust_merged_2['part_of_day'] = result

In [54]:
# Check the confirm part of the day results
df_ords_prods_cust_merged_2['part_of_day'].value_counts()

Afternoon    15267078
Morning      11459102
Evening       5708032
Name: part_of_day, dtype: int64

In [55]:
# Check totals for family status
df_ords_prods_cust_merged_2['fam_status'].value_counts()

married                             22776913
single                               5330769
divorced/widowed                     2774428
living with parents and siblings     1552102
Name: fam_status, dtype: int64

# Create an appropriate visualization to show the distribution of profiles.

In [56]:
# First step is to define what producst are selling the best.
df_ords_prods_cust_merged_2.head()

,order_id,product_id,add_to_cart_order,reordered,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_name,...,number_of_dependants,fam_status,income,region,exclusion_flag,age_group,income_range,parental_status,weekday,part_of_day
0,2,33120,1,1,202279,3,5,9,8.0,Organic Egg Whites,...,3,married,98119,West,non low activity customer,51-60,080000-120000,parent,Thursday,Morning
1,104690,33120,2,1,202279,8,6,10,30.0,Organic Egg Whites,...,3,married,98119,West,non low activity customer,51-60,080000-120000,parent,Friday,Morning
2,132412,33120,1,1,202279,6,5,9,30.0,Organic Egg Whites,...,3,married,98119,West,non low activity customer,51-60,080000-120000,parent,Thursday,Morning
3,2808715,33120,1,1,202279,5,5,13,9.0,Organic Egg Whites,...,3,married,98119,West,non low activity customer,51-60,080000-120000,parent,Thursday,Afternoon
4,2894949,33120,5,0,202279,1,5,9,3.0,Organic Egg Whites,...,3,married,98119,West,non low activity customer,51-60,080000-120000,parent,Thursday,Morning

In [57]:
crosstab = df_ords_prods_cust_merged_2.head(10)

In [58]:
crosstab.to_clipboard()

In [59]:
# Get the amount of sales for each product id
Sales_by_product_id = df_ords_prods_cust_merged_2.groupby('product_id').agg({'prices' : ['min', 'mean', 'max','sum']})

In [62]:
Sales_by_product_id.to_clipboard()

In [60]:
# Get the amount of sales for each product name
Sales_by_product_name = df_ords_prods_cust_merged_2.groupby('product_name').agg({'prices' : ['min', 'mean', 'max','sum']})

In [61]:
Sales_by_product_name.to_clipboard()

In [62]:
# Get the amount of oders for each product name
Product_sales_by_order_number = df_ords_prods_cust_merged_2.groupby('product_name').agg({'order_number' : ['min', 'mean', 'max','sum']})

In [63]:
Product_sales_by_order_number.to_clipboard()

I will use the top 25 best selling items.The reason I will use only the top 25 best selling items is because these 25 items is because it will allow for marketing to create focused marketing campaings to all customers. Also, these 25 items make up 14% of total sales and 10% of total items sold.

In [64]:
# Create a list of top selling products by price
Product_list_1 = ['Banana', 'Bag of Organic Bananas', 'Large Lemon', 'Limes', 'Organic Baby Spinach', 'Organic Strawberries', 'Organic Whole Milk', 'Cucumber Kirby', 'Apple Honeycrisp Organic','Organic Cucumber','Organic Avocado','Asparagus','Organic Baby Carrots','Michigan Organic Kale','Organic Hass Avocado','Organic Tomato Cluster','Organic Blueberries','Organic Zucchini','Half & Half','Carrots','Organic Blackberries','Organic Garlic','Organic Grape Tomatoes','Organic Large Extra Fancy Fuji Apple','Organic Gala Apples']

In [65]:
# Write for loop to flag all tp selling items.

result = []

for value in df_ords_prods_cust_merged_2['product_name']:
    if value in Product_list_1:
        result.append('Top 25 selling product')
    else:
        result.append('Currently not assigned')

In [66]:
result

['Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Currently not assigned',
 'Top 25 selling product',
 'Currently not assigned',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Top 25 selling product',
 'Top 25 selling product',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Top 25 selling product',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Top 25 selling product',
 'Currently not assigned',
 'Top 25 selling product',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Currently not assigned',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Top 25 selling product',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Top 25 selling product',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Top 25 selling product',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Top 25 selling product',
 'Top 25 selling product',
 'Currently not assigned',
 'Top 25 selling product',
 'Top 25 selling product',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Top 25 selling product',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',
 'Currently not assigned',

In [67]:
# Create new column for selling performance
df_ords_prods_cust_merged_2['selling_performance'] = result

In [81]:
# Check results of selling performance
df_ords_prods_cust_merged_2['selling_performance'].value_counts()

Currently not assigned    28964735
Top 25 selling product     3469477
Name: selling_performance, dtype: int64

In [82]:
# Create a subset data set with only top 25 items
df_top_25_selling_items = df_ords_prods_cust_merged_2[df_ords_prods_cust_merged_2['selling_performance']=='Top 25 selling product']

In [83]:
# Check the confirm only showing top 25 items
df_top_25_selling_items['selling_performance'].value_counts()

Top 25 selling product    3469477
Name: selling_performance, dtype: int64

# Key Question #4.A: Are there certain types of products that are more popular than others?

In [1]:
# Create top 25 selling items bar chart
bar_top_25_selling_items = df_top_25_selling_items['product_name'].value_counts().plot.bar(color = sns.color_palette('YlGnBu_r', 25))
plt.tight_layout()

NameError: name 'df_top_25_selling_items' is not defined

In [88]:
# Export top 25 selling items
bar_top_25_selling_items.figure.savefig(os.path.join(path,'04 Analysis','Visualizations','top_25_selling_items.png'))

Checking to see if there is a particular customer group that buys more or shops for the top 25 items more than other groups.

In [89]:
sales_per_age_group = df_top_25_selling_items.groupby('age_group').agg({'order_number':['mean']})

In [90]:
sales_per_age_group

          order_number
                  mean
age_group
18-20        18.201507
21-30        18.234945
31-40        18.603790
41-50        18.276069
51-60        18.345565
61-70        18.263389
71-80        18.286088
80+          18.993192

In [91]:
sales_per_number_of_dependents = df_top_25_selling_items.groupby('parental_status').agg({'order_number':['mean']})

In [92]:
sales_per_number_of_dependents

                order_number
                        mean
parental_status
non parent         18.457275
parent             18.300526

In [93]:
sales_per_income = df_top_25_selling_items.groupby('income_range').agg({'order_number':['mean']})

In [94]:
sales_per_income

              order_number
                      mean
income_range
025000-040000    16.425376
040000-080000    18.473160
080000-120000    18.379550
120000-160000    18.278517
160000-210000    18.689846
210000-523000    20.516320
523000+          18.995604

In [95]:
sales_per_weekday = df_top_25_selling_items.groupby('weekday').agg({'order_number':['mean']})

In [96]:
sales_per_weekday

          order_number
                  mean
weekday
Friday       17.733653
Monday       18.507489
Saturday     17.112215
Sunday       18.156018
Thursday     19.378558
Tuesday      19.197519
Wednesday    19.491206

It does not appear that any particular group should be targeted for the top 25 items so marketing campaings for these items should be for all customers.

# Key questions #4.B: The marketing and sales teams want to know which departments have the highest frequency of product orders.

Second step is to define what departments are selling the best to what customers and when. Searching by departments should give a more specific view as to who to traget for marketing campaigns.

In [97]:
# Get the amount of sales for each department_id
Sales_by_department_id = df_ords_prods_cust_merged_2.groupby('department_id').agg({'prices' : ['min', 'mean', 'max','sum']})

In [98]:
Sales_by_department_id.to_clipboard()

In [99]:
df_ords_prods_cust_merged_2['prices'].value_counts().sort_index()

1.0        115143
1.1        242782
1.2        256276
1.3        425691
1.4        392209
            ...
24.8          410
24.9         5781
25.0        13772
14900.0      4429
99999.0       698
Name: prices, Length: 242, dtype: int64

There are prices of 14,900 and 99,999. Most likely these are outliers. I would consult with the client to make sure but in the case, I will create a subset without these values as they throw off the highest selling departments which indicate which departments to create marketing strategies for.

In [100]:
# Create a loop for items valued at 99,999

result = []

for value in df_ords_prods_cust_merged_2['prices']:
    if value >= 14900: 
        result.append('outlier')
    else: 
        result.append('other')

In [101]:
result

['other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 'other',
 ...]

In [102]:
# Create new column for outliers
df_ords_prods_cust_merged_2['price_range'] = result

In [103]:
# Check results
df_ords_prods_cust_merged_2['price_range'].value_counts()

other      32429085
outlier        5127
Name: price_range, dtype: int64

# I will be splitting my notebook as it is starting to get a bit sluggish. I will export my latest data frame and then continue my note book on notebook labeled "Exercise 4.10 Coding Etiquette & Excel Reporting 1.A."

In [ ]:
# Export latest note book
f_ords_prods_cust_merged_2.to_pickle(os.path.join(path,'02 Data','Prepared Data','orders_products_merged_7.pkl'))